// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CorpCommentReact.Server.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240908105713_SeedData")]
    partial class SeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CorpCommentReact.Server.Models.Feedback", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BadgeLetter")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Company")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DaysAgo")
                        .HasColumnType("int");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UpvoteCount")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Feedbacks");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BadgeLetter = "B",
                            Company = "ByteGrad",
                            DaysAgo = 4,
                            Text = "Hi #ByteGrad, I really like the courses. 😁 I just wish that you would produce more of them and faster. That would be great, as I want to be a dev!",
                            UpvoteCount = 593
                        },
                        new
                        {
                            Id = 2,
                            BadgeLetter = "S",
                            Company = "Starbucks",
                            DaysAgo = 3,
                            Text = "I really wish #Starbucks would use hand wrappers for hot drinks as a standard, I keep burning my hands and am tired of bothering the employee.",
                            UpvoteCount = 563
                        },
                        new
                        {
                            Id = 3,
                            BadgeLetter = "N",
                            Company = "Netflix",
                            DaysAgo = 5,
                            Text = "Since yesterday on mobile #netflix keeps buffering the video, it keeps happening even when I redownload the app. I'm in an area with decent internet btw.",
                            UpvoteCount = 486
                        },
                        new
                        {
                            Id = 4,
                            BadgeLetter = "M",
                            Company = "McDonald's",
                            DaysAgo = 2,
                            Text = "It's a real shame that my local #mcdonald's removed milkshakes from the menu. They were the reason I go to McDonald's. 😩 Please bring them back!",
                            UpvoteCount = 377
                        },
                        new
                        {
                            Id = 5,
                            BadgeLetter = "A",
                            Company = "Amazon",
                            DaysAgo = 1,
                            Text = "I'm an #amazon prime member but don't really watch the prime video offering. Instead of that I would want an option for even faster delivery 😎",
                            UpvoteCount = 156
                        },
                        new
                        {
                            Id = 6,
                            BadgeLetter = "N",
                            Company = "Netflix",
                            DaysAgo = 1,
                            Text = "Would be great if #netflix could announce content removals further ahead. 😊 I don't want to get into a show only for it to be gone soon. Thanks.",
                            UpvoteCount = 88
                        },
                        new
                        {
                            Id = 7,
                            BadgeLetter = "M",
                            Company = "Microsoft",
                            DaysAgo = 1,
                            Text = "I've been using #microsoft teams for a couple of weeks now and one thing that really sticks out is that navigation is too difficult. Please simplify it.",
                            UpvoteCount = 41
                        },
                        new
                        {
                            Id = 8,
                            BadgeLetter = "N",
                            Company = "Nike",
                            DaysAgo = 5,
                            Text = "Hi #nike I love your running shoes but it's very difficult to return them after a purchase. Had to do a lot of phone calls to make it work. Thanks 👍",
                            UpvoteCount = 39
                        },
                        new
                        {
                            Id = 9,
                            BadgeLetter = "M",
                            Company = "McDonald's",
                            DaysAgo = 2,
                            Text = "#mcdonald's the past few times I've been some items were missing from my order. Only noticed this when I got home. Straws, nuggets, fries, they missed.",
                            UpvoteCount = 22
                        },
                        new
                        {
                            Id = 10,
                            BadgeLetter = "A",
                            Company = "Adidas",
                            DaysAgo = 3,
                            Text = "I like your website #adidas, but your sizing guide needs some work. It suggested an L for me but when it arrived it was too big. Still kept it btw 😎",
                            UpvoteCount = 9
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
